---
  - name: Add apt key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com
    tags: install

  - name: Add apt repository
    apt_repository:
      repo: "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
      state: present
    tags: install

  - name: Install mongodb
    apt:
      name: mongodb-org
      state: present
    tags: install

  - name: Configure service
    systemd:
      name: mongod
      enabled: yes
    tags: install
